### ISSUE TITLE
Improve error message when helper package managers are not available

### ISSUE THREAD

**Issue by glennmatthews** [glennmatthews/cot#57]
```bash
$ cot inject-config csr1000v-universalk9.16.03.01a-w-ios-config.ova -o csr1000v-universalk9.16.03.01a-w-1Int-BaseConfig-ios-config.ova -c csr1000v-Config.txt
    INFO: Loading 'csr1000v-universalk9.16.03.01a-w-ios-config.ova' as OVF
    INFO: OVF version is 1.x
    INFO: OVF product class com.cisco.csr1000v --> platform CSR1000V
No helper available or installable!
```

This is failing because none of the ISO helpers (mkisofs/genisoimage/xorriso) are available and the user is on a Mac that does not have MacPorts installed - but the error message fails to make that clear, and should be improved.

**Comment by glennmatthews** [comment]
Improved message (as generated on a Mac):

```python
>>> COT.helpers.helper_select(['mkisofs', 'genisoimage', 'xorriso'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "COT/helpers/helper.py", line 640, in helper_select
    raise HelperNotFoundError(msg)
COT.helpers.helper.HelperNotFoundError: No helper in list ['mkisofs', 'genisoimage', 'xorriso'] is available or installable!
You may want to install MacPorts (https://www.macports.org/) so that COT can use it to install helpers as needed.
```

**Comment by glennmatthews** [comment]
Improved message (as faked out for Linux):

```python
>>> sys.platform = 'linux2'
>>> 
>>> COT.helpers.helper_select(['mkisofs', 'genisoimage', 'xorriso'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "COT/helpers/helper.py", line 640, in helper_select
    raise HelperNotFoundError(msg)
COT.helpers.helper.HelperNotFoundError: No helper in list ['mkisofs', 'genisoimage', 'xorriso'] is available or installable!
COT is aware of 'apt-get' and 'yum' but neither is present?
```
