### ISSUE TITLE
Distutils Error in version.py

### ISSUE THREAD

**Issue by captainCrench** [glennmatthews/cot#76]
When using cot, I'm getting the following error:

Traceback (most recent call last):
  File "/usr/bin/cot", line 11, in <module>
    load_entry_point('cot==2.2.0', 'console_scripts', 'cot')()
  File "build/bdist.linux-x86_64/egg/COT/ui/cli.py", line 717, in main
  File "build/bdist.linux-x86_64/egg/COT/ui/cli.py", line 324, in run
  File "build/bdist.linux-x86_64/egg/COT/ui/cli.py", line 601, in main
  File "build/bdist.linux-x86_64/egg/COT/commands/deploy_esxi.py", line 363, in run
  File "/usr/lib64/python2.7/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: 'NoneType' object has no attribute 'version'

**Comment by glennmatthews** [comment]
Sorry for the delayed response! Can you confirm whether you have `ovftool` installed?
